---
- hosts: mysql-node
  remote_user: "{{ osuser }}"
  become: yes
  become_user: root
  gather_facts: false
  vars_files:
    - mysql_nodes.yml

  pre_tasks:

  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when:
    - output.stdout != ""
    - output.stdout != "\r\n"
  - name: Gathering Facts
    setup:


  tasks:

    - name: Create  ext4 filesystem
      filesystem:
        fstype: ext4
        dev: "{{ disk }}"
        force: no
        opts: -E lazy_itable_init=0,lazy_journal_init=0,discard

    - name: Mount FS
      mount:
        path: "{{ mountdir }}"
        src: "{{ disk }}"
        fstype: ext4
        opts: discard
        state: mounted

    - name: copy gpgkey
      copy:
        src: gpgkey
        dest: /tmp
        owner: root
        mode: 644

    - name: import gpgkey
      shell: apt-key add /tmp/gpgkey


    - name: Remove repo
      file:
        path: /etc/apt/sources.list.d/repo_mysql_com_apt_ubuntu.list
        state: absent

    - name: Install  MySQL repo
      apt_repository:
        repo: deb http://repo.mysql.com/apt/ubuntu/ bionic "{{ mysqlver }}"
        state: present

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes

    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Install MySQL-python
      apt:
        name: python-mysqldb
        state: present

    - name: Stop MySQL
      systemd:
        name: mysql
        state: stopped
      tags: init-setup

    - name: Remove datadir
      file:
        path: "{{ mysqldir }}"
        state: "{{ item }}"
        owner: mysql
        group: mysql
      with_items:
        - absent
        - directory
      tags: init-setup

    - name: Remove datadir
      file:
        path: "/mnt/logs"
        state: "{{ item }}"
        owner: mysql
        group: mysql
      with_items:
        - directory
      tags: init-setup

    - name: Install  apparmor-utils
      apt:
        name: apparmor-utils
        state: present

    - name: Disable apparmor for mysqld
      shell: >
         aa-complain /usr/sbin/mysqld
      ignore_errors: yes
      tags: init-setup

    - name: Init datadir
      shell: >
        mysqld --no-defaults --initialize-insecure --datadir="{{ mysqldir }}" --user=mysql
      tags: init-setup
