---
- hosts: mysql-node
  remote_user: vadim
  become: yes
  become_user: root
  vars_files:
    - mysql_nodes.yml
  tasks:
        - name: Find existing UUID if it exists
          shell: >
              grep "^loose-group_replication_group_name" /etc/my.cnf |
              cut -d '"' -f2
          run_once: true
          changed_when: false
          register: existing_cluster_uuid

        - name: Generate UUID incase no previous value was present
          command: uuidgen
          run_once: true
          changed_when: false
          register: new_cluster_uuid

        - name: Generate global mysql.cnf file for group replication
          template:
            src: mysql.cnf.j2
            dest: /etc/my.cnf
            owner: root
            group: root
            mode: "0644"
            backup: true

        - name: Restart MySQL
          systemd:
            name: mysqld
            state: restarted
