---
- hosts: node
  remote_user: "{{ osuser }}"
  become: yes
  become_user: root
  vars_files:
    - mysql_nodes.yml
  tasks:

    - import_tasks: root_tasks.yml

    - import_tasks: pxc_replication.yml

    - name: Generate MySQL replication user script
      template:
        src: user.sql.j2
        dest: "/tmp/user.sql"
      when:
        - inventory_hostname == ansible_play_hosts[0]

    - name: Set up replication user
      shell: >
        cat /tmp/user.sql | mysql
      when:
        - inventory_hostname == ansible_play_hosts[0]
