---
- hosts: node
  remote_user: "{{ osuser }}"
  become: yes
  become_user: root
  gather_facts: false
  vars_files:
    - mysql_nodes.yml

  pre_tasks:

  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when:
    - output.stdout != ""
    - output.stdout != "\r\n"
  - name: Gathering Facts
    setup:


  tasks:

    - name: Create  ext4 filesystem
      filesystem:
        fstype: ext4
        dev: "{{ disk }}"
        force: no
        opts: -E lazy_itable_init=0,lazy_journal_init=0,discard
      when: disk is defined

    - name: Mount FS
      mount:
        path: "{{ mountdir }}"
        src: "{{ disk }}"
        fstype: ext4
        opts: discard
        state: mounted
      when: disk is defined
      tags: mount    
 
    - name: create install dir
      file:
        path: "{{ installdir }}"
        state: "{{ item }}"
      with_items:
        - directory

    - name: Download Server
      get_url:
        url: "https://dev.mysql.com/get/Downloads/MySQL-{{ mysqlver }}/{{ mysqlbin }}.tar.gz"
        dest: "{{ installdir }}"

    - name: Install Server
      unarchive:
        src: "{{ installdir }}/{{ mysqlbin }}.tar.gz"
        dest: "{{ installdir }}"
        remote_src: yes

    - name: Install MySQL-python
      apt:
        name: python-mysqldb
        state: present



    - name: Stop MySQL
      shell: >
        "{{ installdir }}/{{ mysqlbin }}/bin/mysqladmin" shutdown --socket=/tmp/mysql.sock
      ignore_errors: yes

    - name: Remove datadir
      file:
        path: "{{ mountdir }}/{{ mysqldir }}"
        state: "{{ item }}"
        owner: mysql
        group: mysql
      with_items:
        - absent
        - directory

    - name: Init datadir
      shell: >
        "{{ installdir }}/{{ mysqlbin }}/bin/mysqld" --no-defaults --initialize-insecure --datadir="{{ mountdir }}/{{ mysqldir }}" --user=mysql
      tags: init-setup

    - name: Generate systemctl file
      template:
        src: mysql.service.j2
        dest: /etc/systemd/system/mysql-cd.service
        owner: root
        group: root
        mode: "0644"
        backup: false

    - name: Generate client my.cnf
      template:
        src: my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: "0644"
        backup: false

    - name: Reload systemd
      shell: systemctl daemon-reload

    - name: enable mysql systemd
      shell: systemctl enable mysql-cd

# vim: set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
