---
- hosts: worker
  remote_user: "{{ osuser }}"
  become: yes
  become_user: root
  gather_facts: true
  vars_files:
    - config_nodes.yml

  tasks:

    - name: Hostname
      hostname: name="worknode-{{ play_hosts.index(inventory_hostname)|int+1 }}"

- hosts: all
  remote_user: "{{ osuser }}"
  become: yes
  become_user: root
  gather_facts: false
  serial: 5
  vars_files:
    - config_nodes.yml

  pre_tasks:

  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when:
    - output.stdout != ""
    - output.stdout != "\r\n"
  - name: Gathering Facts
    setup:


  tasks:

    - import_tasks: network_tasks.yml

    - name: Install external script
      shell: >
        curl -sL https://gist.githubusercontent.com/alexellis/7315e75635623667c32199368aa11e95/raw/b025dfb91b43ea9309ce6ed67e24790ba65d7b67/kube.sh | sudo sh

    - name: Disable swap
      shell: >
        swapoff -a

    - name: Fix sysctl
      shell: sysctl net.bridge.bridge-nf-call-iptables=1

    - name: Kernel config
      shell: apt-get install linux-image-4.15.0-38-generic -y

    - name: Reset Kubernetes component
      shell: "kubeadm reset --force"

