---
- hosts: node
  remote_user: "{{ osuser }}"
  become: yes
  become_user: root
  gather_facts: false
  vars_files:
    - mysql_nodes.yml

  pre_tasks:

  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when:
    - output.stdout != ""
    - output.stdout != "\r\n"
  - name: Gathering Facts
    setup:


  tasks:

    - name: Create  ext4 filesystem
      filesystem:
        fstype: ext4
        dev: "{{ disk }}"
        force: no
        opts: -E lazy_itable_init=0,lazy_journal_init=0,discard
      when: disk is defined

    - name: Mount FS
      mount:
        path: "{{ mountdir }}"
        src: "{{ disk }}"
        fstype: ext4
        opts: discard
        state: mounted
      when: disk is defined

    - name: Install Percona Repo
      shell: >
        wget -P /tmp https://repo.percona.com/apt/percona-release_latest.generic_all.deb

    - name: Install Percona Repo
      shell: >
        dpkg -i /tmp/percona-release_latest.generic_all.deb

    - name: Update and upgrade apt packages
      apt:
        update_cache: yes

    - name: Install PXC
      apt:
        name: percona-xtradb-cluster-57
        state: present

    - name: Install MySQL-python
      apt:
        name: python-mysqldb
        state: present

    - name: Stop MySQL
      systemd:
        name: mysql
        state: stopped
      tags: init-setup

    - name: Remove datadir
      file:
        path: "{{ mysqldir }}"
        state: "{{ item }}"
        owner: mysql
        group: mysql
      with_items:
        - absent
        - directory
      tags: init-setup

    - name: Remove datadir
      file:
        path: "/mnt/logs"
        state: "{{ item }}"
        owner: mysql
        group: mysql
      with_items:
        - directory
      tags: init-setup

    - name: Init datadir
      shell: >
        mysqld --no-defaults --initialize-insecure --datadir="{{ mysqldir }}" --user=mysql
      tags: init-setup
